security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
  web-service:
    password: ${WS_AUTH_PASS}
    username: ${WS_AUTH_USER}
icon:
  host: ${ORDS_HOST}
  username: ${ORDS_USERNAME}
  password: ${ORDS_PASSWORD}
  hsr-service-url: ${HSR_SERVICE_URL}
  hsr-queue: ${HSR_QUEUE_NAME}
  hsr-routing-key: ${HSR_ROUTING_KEY}
  ping-queue: ${PING_QUEUE_NAME}
  ping-routing-key: ${PING_ROUTING_KEY}
  exchange-name: ${RABBIT_EXCHANGE_NAME}

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
