security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
icon:
  host: ${ORDS_HOST}
  username: ${ORDS_USERNAME}
  password: ${ORDS_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health