security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}

test:
  password: ${BASIC_AUTH_PASS}
  username: ${BASIC_AUTH_USER}
  api-host-1: ${API_HOST_1}
  api-host-2: ${API_HOST_2}
  api-host-MyFiles: ${API_HOST_MyFiles}
  api-host-Biometrics: ${API_HOST_Biometrics}